Feature query update
uisendy/Vet-clinic-database pull request #2
Opened 2022-10-20 19:31 UTC by uisendy

In this milestone,  transactions to update and delete records were performed. aggregate functions and GROUP BY were also used to answer analytical questions.

The following was performed carefully in this activity. 

1. Add a new Column to the Animal Table and called it "species"
2. Insertion of more data into the animal table. The total Data after insertion is 11. 
3. Use Transaction to perform a specific task with the table concerning the update, query, deletion, rollover, savepoint and commit, 
4. Using Aggregate functions to answer the specific questions concerning the take. See the queries.sql for the questions in the comment and the specific queries. 

**Screenshots of play and queries**
![9](https://user-images.githubusercontent.com/95294594/197040486-ee223c7b-f9d7-4b75-b106-fe8e51ee3906.PNG)
![10](https://user-images.githubusercontent.com/95294594/197040498-44b24823-35ac-400a-8b43-5984aa3adb7f.PNG)
![11](https://user-images.githubusercontent.com/95294594/197040507-95709457-fcbf-49e9-87f2-473c9ac02047.PNG)
![12](https://user-images.githubusercontent.com/95294594/197040509-a8b345b9-cc39-4226-9d7f-bf91d6f22cfb.PNG)
![13](https://user-images.githubusercontent.com/95294594/197040511-fdb8ed3b-ea5a-4635-95db-4787c013085e.PNG)
![aggregate-1](https://user-images.githubusercontent.com/95294594/197040515-35c32088-39ef-4dc6-af96-902b3ea462b4.PNG)
![aggregate-2](https://user-images.githubusercontent.com/95294594/197040519-e6d8d9bd-17ed-48bc-98cf-992981fb2e8a.PNG)
![aggregate-3](https://user-images.githubusercontent.com/95294594/197040520-ea91d5bc-9a41-425a-b8be-f44c60b83bd3.PNG)
![aggregate-4](https://user-images.githubusercontent.com/95294594/197040524-6adcdef6-73f0-45bd-ae48-951cb27e9709.PNG)
![aggregate-5](https://user-images.githubusercontent.com/95294594/197040526-f6a1a5a1-9b6a-4bc0-9239-8d4ea2a67173.PNG)
![aggregate-7](https://user-images.githubusercontent.com/95294594/197040531-982a1532-0da3-45f9-98a3-d7db4c846e91.PNG)

2022-10-20 20:10 UTC, RolandM99 requested changes
Hi @uisendy  , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)

### To highlight 💯 
- Good commit message ✔️ 
- No Linter errors ✔️ 
- Follow Github flow ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on @Rolandm99 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-20 20:10 UTC, RolandM99 commented on data.sql
> +        ('Angemon', '2005-06-12', 1, true, 45)
- [ ] The weight of these animals should be negative. kindly, change their values into negative values.

2022-10-20 20:10 UTC, RolandM99 commented on queries.sql
> +-- Inside a Transaction
- [ ] Kindly, create the queries to update the `animals` table by setting the species column to unspecified, then roll back the change. Take a look on the code snippet below:
```sql
BEGIN; -- start transaction
   UPDATE animals
   SET species = 'unspecified';
   SELECT species from animals; 
   ROLLBACK;
   SELECT species from animals;
```

2022-10-20 23:48 UTC, MahmoudBakr23 approved these changes
Hi @uisendy 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 

**Highlights**
- Well done making the required changes from the previous reviewer

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-22 15:02 UTC, closed without merging

2022-12-10 21:30 UTC, zieeco reviewed
# status: APPROVED :green_circle: :100: 

Hi, @uisendy , 


![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f78543078657a514755357843444a754350652f67697068792e676966](https://user-images.githubusercontent.com/85113567/164945882-0a9554ea-956c-4fa0-a95c-379285283c1d.gif)


Good job so far 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights ⚡ 

✅ Descriptive PR 👍 
✅ Nice query🔥 
✅ Linters are passing 👏 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._